/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HandleidingRouteImport } from './routes/handleiding'
import { Route as IndexRouteImport } from './routes/index'

const HandleidingRoute = HandleidingRouteImport.update({
  id: '/handleiding',
  path: '/handleiding',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handleiding': typeof HandleidingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handleiding': typeof HandleidingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handleiding': typeof HandleidingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/handleiding'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/handleiding'
  id: '__root__' | '/' | '/handleiding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandleidingRoute: typeof HandleidingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/handleiding': {
      id: '/handleiding'
      path: '/handleiding'
      fullPath: '/handleiding'
      preLoaderRoute: typeof HandleidingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandleidingRoute: HandleidingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
